### ISSUE TITLE
pod install errors out

### ISSUE THREAD

**Issue by anthonylai** [ParsePlatform/ParseFacebookUtils-iOS#76]
Xcode: 8.1
pod: 1.1.1

pod install fails.  

Please kindly assist.

pod install

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.3.5
Ruby lib dir : /Users/aslai/.rvm/rubies/ruby-2.1.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b9ede68d8d76a4c9704b4436975158a6fa6a4293
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `root' for nil:NilClass
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:160:in `root_spec'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:173:in `predownloaded?'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `each'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:111:in `install!'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Users/aslai/.rvm/gems/ruby-2.1.2/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/Users/aslai/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/aslai/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/aslai/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/aslai/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Abderezai** [comment]
Was this ever resolved for you?

**Comment by anthonylai** [comment]
Yep, I think it was resolved by setting the ios platform in the podfile:

platform :ios, '10.1'

Hope this is helpful to you.
